name: Cypress Run Tests


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-artifact
          path: ./frontend

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build and start
        run: npm run dev
        working-directory: ./frontend

      - name: Cypress run
        uses: cypress-io/github-action@v6