name: Cypress Run Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build and start
        run: |
          npm run build
          npm start
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
